# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/jyunmau/PycharmProjects/Diatom-classification/Qt_Ui/featureReadWid.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_featureReadWidget(object):
    def setupUi(self, featureReadWidget):
        featureReadWidget.setObjectName("featureReadWidget")
        featureReadWidget.resize(500, 350)
        self.horizontalLayoutWidget = QtWidgets.QWidget(featureReadWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 481, 341))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.geometricCheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.geometricCheckBox.sizePolicy().hasHeightForWidth())
        self.geometricCheckBox.setSizePolicy(sizePolicy)
        self.geometricCheckBox.setChecked(True)
        self.geometricCheckBox.setAutoExclusive(False)
        self.geometricCheckBox.setObjectName("geometricCheckBox")
        self.horizontalLayout_6.addWidget(self.geometricCheckBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.glcmCheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.glcmCheckBox.setChecked(True)
        self.glcmCheckBox.setObjectName("glcmCheckBox")
        self.horizontalLayout_5.addWidget(self.glcmCheckBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.fdCheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.fdCheckBox.setObjectName("fdCheckBox")
        self.horizontalLayout_4.addWidget(self.fdCheckBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.hogCheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.hogCheckBox.setObjectName("hogCheckBox")
        self.horizontalLayout_3.addWidget(self.hogCheckBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.siftCheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.siftCheckBox.setObjectName("siftCheckBox")
        self.horizontalLayout.addWidget(self.siftCheckBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbpCheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.lbpCheckBox.setChecked(True)
        self.lbpCheckBox.setObjectName("lbpCheckBox")
        self.horizontalLayout_2.addWidget(self.lbpCheckBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_9.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.featureNumSpinBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.featureNumSpinBox.setMinimum(-2)
        self.featureNumSpinBox.setMaximum(600)
        self.featureNumSpinBox.setProperty("value", 450)
        self.featureNumSpinBox.setObjectName("featureNumSpinBox")
        self.horizontalLayout_7.addWidget(self.featureNumSpinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_11.addWidget(self.label_2)
        self.featureSelectionComboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.featureSelectionComboBox.setObjectName("featureSelectionComboBox")
        self.featureSelectionComboBox.addItem("")
        self.featureSelectionComboBox.addItem("")
        self.featureSelectionComboBox.addItem("")
        self.horizontalLayout_11.addWidget(self.featureSelectionComboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.normalizeCheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.normalizeCheckBox.setChecked(True)
        self.normalizeCheckBox.setObjectName("normalizeCheckBox")
        self.horizontalLayout_10.addWidget(self.normalizeCheckBox)
        self.regularizeCheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.regularizeCheckBox.setChecked(True)
        self.regularizeCheckBox.setObjectName("regularizeCheckBox")
        self.horizontalLayout_10.addWidget(self.regularizeCheckBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.transformCheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.transformCheckBox.setChecked(True)
        self.transformCheckBox.setObjectName("transformCheckBox")
        self.horizontalLayout_8.addWidget(self.transformCheckBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9.addLayout(self.verticalLayout_3)

        self.retranslateUi(featureReadWidget)
        QtCore.QMetaObject.connectSlotsByName(featureReadWidget)

    def retranslateUi(self, featureReadWidget):
        _translate = QtCore.QCoreApplication.translate
        featureReadWidget.setWindowTitle(_translate("featureReadWidget", "特征组合设置"))
        self.geometricCheckBox.setText(_translate("featureReadWidget", "基于统计和几何的形状特征"))
        self.glcmCheckBox.setText(_translate("featureReadWidget", "基于灰度共生矩阵的纹理特征"))
        self.fdCheckBox.setText(_translate("featureReadWidget", "傅立叶描述子特征"))
        self.hogCheckBox.setText(_translate("featureReadWidget", "HOG算子特征"))
        self.siftCheckBox.setText(_translate("featureReadWidget", "SIFT算子特征"))
        self.lbpCheckBox.setText(_translate("featureReadWidget", "LBP算子特征"))
        self.label.setText(_translate("featureReadWidget", "特征维数:"))
        self.label_2.setText(_translate("featureReadWidget", "特征选择方法:"))
        self.featureSelectionComboBox.setItemText(0, _translate("featureReadWidget", "filter"))
        self.featureSelectionComboBox.setItemText(1, _translate("featureReadWidget", "wrapper"))
        self.featureSelectionComboBox.setItemText(2, _translate("featureReadWidget", "embedded"))
        self.normalizeCheckBox.setText(_translate("featureReadWidget", "归一化"))
        self.regularizeCheckBox.setText(_translate("featureReadWidget", "正则化"))
        self.transformCheckBox.setText(_translate("featureReadWidget", "数据变换（默认第一特征）"))
