# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/jyunmau/PycharmProjects/Diatom-classification/Qt_Ui/MainWin.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 931, 631))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.infoLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.infoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.infoLabel.setObjectName("infoLabel")
        self.verticalLayout.addWidget(self.infoLabel)
        self.graphicsView = QtWidgets.QGraphicsView(self.horizontalLayoutWidget)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.dataSetRadioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.dataSetRadioButton.setObjectName("dataSetRadioButton")
        self.horizontalLayout_2.addWidget(self.dataSetRadioButton)
        self.dataSetButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.dataSetButton.setObjectName("dataSetButton")
        self.horizontalLayout_2.addWidget(self.dataSetButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.imageRadioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.imageRadioButton.setObjectName("imageRadioButton")
        self.horizontalLayout_10.addWidget(self.imageRadioButton)
        self.imageButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.imageButton.setObjectName("imageButton")
        self.horizontalLayout_10.addWidget(self.imageButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.featureFetchRadioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.featureFetchRadioButton.setObjectName("featureFetchRadioButton")
        self.horizontalLayout_6.addWidget(self.featureFetchRadioButton)
        self.featureFetchButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.featureFetchButton.setObjectName("featureFetchButton")
        self.horizontalLayout_6.addWidget(self.featureFetchButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.featureReadRadioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.featureReadRadioButton.setObjectName("featureReadRadioButton")
        self.horizontalLayout_9.addWidget(self.featureReadRadioButton)
        self.featureReadButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.featureReadButton.setObjectName("featureReadButton")
        self.horizontalLayout_9.addWidget(self.featureReadButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.modelRadioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.modelRadioButton.setObjectName("modelRadioButton")
        self.horizontalLayout_3.addWidget(self.modelRadioButton)
        self.modelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.modelButton.setObjectName("modelButton")
        self.horizontalLayout_3.addWidget(self.modelButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.predictRadioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.predictRadioButton.setObjectName("predictRadioButton")
        self.horizontalLayout_11.addWidget(self.predictRadioButton)
        self.predictButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.predictButton.setObjectName("predictButton")
        self.horizontalLayout_11.addWidget(self.predictButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.startButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.startButton.setObjectName("startButton")
        self.verticalLayout_2.addWidget(self.startButton)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 950, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.infoLabel.setText(_translate("MainWindow", "等待显示图片..."))
        self.dataSetRadioButton.setText(_translate("MainWindow", "加载图片集"))
        self.dataSetButton.setText(_translate("MainWindow", "设置路径"))
        self.imageRadioButton.setText(_translate("MainWindow", "图片预处理"))
        self.imageButton.setText(_translate("MainWindow", "预处理设置"))
        self.featureFetchRadioButton.setText(_translate("MainWindow", "特征提取"))
        self.featureFetchButton.setText(_translate("MainWindow", "设置特征参数"))
        self.featureReadRadioButton.setText(_translate("MainWindow", "特征组合"))
        self.featureReadButton.setText(_translate("MainWindow", "设置组合方式"))
        self.modelRadioButton.setText(_translate("MainWindow", "模型训练"))
        self.modelButton.setText(_translate("MainWindow", "设置模型参数"))
        self.predictRadioButton.setText(_translate("MainWindow", "图片预测"))
        self.predictButton.setText(_translate("MainWindow", "设置预测参数"))
        self.startButton.setText(_translate("MainWindow", "开始"))
