# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/jyunmau/PycharmProjects/Diatom-classification/Qt_Ui/MainWin.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 931, 631))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.infoLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.infoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.infoLabel.setObjectName("infoLabel")
        self.verticalLayout.addWidget(self.infoLabel)
        self.imageLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageLabel.sizePolicy().hasHeightForWidth())
        self.imageLabel.setSizePolicy(sizePolicy)
        self.imageLabel.setBaseSize(QtCore.QSize(600, 600))
        self.imageLabel.setText("")
        self.imageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imageLabel.setObjectName("imageLabel")
        self.verticalLayout.addWidget(self.imageLabel)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.dataSetCheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.dataSetCheckBox.setChecked(True)
        self.dataSetCheckBox.setObjectName("dataSetCheckBox")
        self.horizontalLayout_2.addWidget(self.dataSetCheckBox)
        self.dataSetButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.dataSetButton.setObjectName("dataSetButton")
        self.horizontalLayout_2.addWidget(self.dataSetButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.imageCheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.imageCheckBox.setChecked(True)
        self.imageCheckBox.setObjectName("imageCheckBox")
        self.horizontalLayout_10.addWidget(self.imageCheckBox)
        self.imageButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.imageButton.setObjectName("imageButton")
        self.horizontalLayout_10.addWidget(self.imageButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.featureFetchCheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.featureFetchCheckBox.setChecked(True)
        self.featureFetchCheckBox.setObjectName("featureFetchCheckBox")
        self.horizontalLayout_6.addWidget(self.featureFetchCheckBox)
        self.featureFetchButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.featureFetchButton.setObjectName("featureFetchButton")
        self.horizontalLayout_6.addWidget(self.featureFetchButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.featureReadCheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.featureReadCheckBox.setObjectName("featureReadCheckBox")
        self.horizontalLayout_9.addWidget(self.featureReadCheckBox)
        self.featureReadButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.featureReadButton.setObjectName("featureReadButton")
        self.horizontalLayout_9.addWidget(self.featureReadButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.modelCheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.modelCheckBox.setObjectName("modelCheckBox")
        self.horizontalLayout_3.addWidget(self.modelCheckBox)
        self.modelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.modelButton.setObjectName("modelButton")
        self.horizontalLayout_3.addWidget(self.modelButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.predictCheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.predictCheckBox.setObjectName("predictCheckBox")
        self.horizontalLayout_11.addWidget(self.predictCheckBox)
        self.predictButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.predictButton.setObjectName("predictButton")
        self.horizontalLayout_11.addWidget(self.predictButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.startButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.startButton.setObjectName("startButton")
        self.verticalLayout_2.addWidget(self.startButton)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 950, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "基于多特征组合的硅藻识别演示程序"))
        self.infoLabel.setText(_translate("MainWindow", "等待显示图片..."))
        self.dataSetCheckBox.setText(_translate("MainWindow", "加载图片集"))
        self.dataSetButton.setText(_translate("MainWindow", "设置路径"))
        self.imageCheckBox.setText(_translate("MainWindow", "图片预处理"))
        self.imageButton.setText(_translate("MainWindow", "预处理设置"))
        self.featureFetchCheckBox.setText(_translate("MainWindow", "特征提取"))
        self.featureFetchButton.setText(_translate("MainWindow", "设置特征参数"))
        self.featureReadCheckBox.setText(_translate("MainWindow", "特征组合"))
        self.featureReadButton.setText(_translate("MainWindow", "设置组合方式"))
        self.modelCheckBox.setText(_translate("MainWindow", "模型训练"))
        self.modelButton.setText(_translate("MainWindow", "设置模型参数"))
        self.predictCheckBox.setText(_translate("MainWindow", "图片预测"))
        self.predictButton.setText(_translate("MainWindow", "设置预测参数"))
        self.startButton.setText(_translate("MainWindow", "开始"))
