# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/jyunmau/PycharmProjects/Diatom-classification/Qt_Ui/modelWid.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_modelWIdget(object):
    def setupUi(self, modelWIdget):
        modelWIdget.setObjectName("modelWIdget")
        modelWIdget.resize(500, 350)
        self.verticalLayoutWidget = QtWidgets.QWidget(modelWIdget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 481, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.saveCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.saveCheckBox.setChecked(True)
        self.saveCheckBox.setObjectName("saveCheckBox")
        self.horizontalLayout_4.addWidget(self.saveCheckBox)
        self.crossCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.crossCheckBox.setChecked(True)
        self.crossCheckBox.setObjectName("crossCheckBox")
        self.horizontalLayout_4.addWidget(self.crossCheckBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.knnRadioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.knnRadioButton.setChecked(True)
        self.knnRadioButton.setObjectName("knnRadioButton")
        self.horizontalLayout_3.addWidget(self.knnRadioButton)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.knnNeighborSpinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.knnNeighborSpinBox.setMaximum(7)
        self.knnNeighborSpinBox.setProperty("value", 5)
        self.knnNeighborSpinBox.setObjectName("knnNeighborSpinBox")
        self.verticalLayout_8.addWidget(self.knnNeighborSpinBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.knnAlgorithmComboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.knnAlgorithmComboBox.setObjectName("knnAlgorithmComboBox")
        self.knnAlgorithmComboBox.addItem("")
        self.knnAlgorithmComboBox.addItem("")
        self.knnAlgorithmComboBox.addItem("")
        self.knnAlgorithmComboBox.addItem("")
        self.verticalLayout_2.addWidget(self.knnAlgorithmComboBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.svmRadioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.svmRadioButton.setObjectName("svmRadioButton")
        self.horizontalLayout.addWidget(self.svmRadioButton)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.svmCSpinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.svmCSpinBox.setMinimum(1)
        self.svmCSpinBox.setMaximum(5)
        self.svmCSpinBox.setSingleStep(1)
        self.svmCSpinBox.setProperty("value", 2)
        self.svmCSpinBox.setObjectName("svmCSpinBox")
        self.verticalLayout_3.addWidget(self.svmCSpinBox)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.svmGammaSpinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.svmGammaSpinBox.setSingleStep(1)
        self.svmGammaSpinBox.setProperty("value", 9)
        self.svmGammaSpinBox.setDisplayIntegerBase(10)
        self.svmGammaSpinBox.setObjectName("svmGammaSpinBox")
        self.verticalLayout_4.addWidget(self.svmGammaSpinBox)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.annRadioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.annRadioButton.setObjectName("annRadioButton")
        self.horizontalLayout_2.addWidget(self.annRadioButton)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.annActivationComboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.annActivationComboBox.setObjectName("annActivationComboBox")
        self.annActivationComboBox.addItem("")
        self.annActivationComboBox.addItem("")
        self.annActivationComboBox.addItem("")
        self.annActivationComboBox.addItem("")
        self.verticalLayout_7.addWidget(self.annActivationComboBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.annSolverComboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.annSolverComboBox.setObjectName("annSolverComboBox")
        self.annSolverComboBox.addItem("")
        self.annSolverComboBox.addItem("")
        self.annSolverComboBox.addItem("")
        self.verticalLayout_6.addWidget(self.annSolverComboBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.annRateSpinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.annRateSpinBox.setMinimum(1)
        self.annRateSpinBox.setProperty("value", 1)
        self.annRateSpinBox.setObjectName("annRateSpinBox")
        self.verticalLayout_5.addWidget(self.annRateSpinBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(modelWIdget)
        QtCore.QMetaObject.connectSlotsByName(modelWIdget)

    def retranslateUi(self, modelWIdget):
        _translate = QtCore.QCoreApplication.translate
        modelWIdget.setWindowTitle(_translate("modelWIdget", "分类器训练设置"))
        self.saveCheckBox.setText(_translate("modelWIdget", "是否保存模型"))
        self.crossCheckBox.setText(_translate("modelWIdget", "是否交叉验证"))
        self.knnRadioButton.setText(_translate("modelWIdget", "KNN"))
        self.label_7.setText(_translate("modelWIdget", "n_neighbors："))
        self.label.setText(_translate("modelWIdget", "algorithm："))
        self.knnAlgorithmComboBox.setItemText(0, _translate("modelWIdget", "auto"))
        self.knnAlgorithmComboBox.setItemText(1, _translate("modelWIdget", "ball_tree"))
        self.knnAlgorithmComboBox.setItemText(2, _translate("modelWIdget", "kd_tree"))
        self.knnAlgorithmComboBox.setItemText(3, _translate("modelWIdget", "brute"))
        self.svmRadioButton.setText(_translate("modelWIdget", "SVM"))
        self.label_2.setText(_translate("modelWIdget", "C："))
        self.label_3.setText(_translate("modelWIdget", "gamma(1e-3)："))
        self.annRadioButton.setText(_translate("modelWIdget", "ANN"))
        self.label_4.setText(_translate("modelWIdget", "activation："))
        self.annActivationComboBox.setItemText(0, _translate("modelWIdget", "relu"))
        self.annActivationComboBox.setItemText(1, _translate("modelWIdget", "logistic"))
        self.annActivationComboBox.setItemText(2, _translate("modelWIdget", "tanh"))
        self.annActivationComboBox.setItemText(3, _translate("modelWIdget", "identity"))
        self.label_5.setText(_translate("modelWIdget", "solver："))
        self.annSolverComboBox.setItemText(0, _translate("modelWIdget", "adam"))
        self.annSolverComboBox.setItemText(1, _translate("modelWIdget", "sgd"))
        self.annSolverComboBox.setItemText(2, _translate("modelWIdget", "lbfgs"))
        self.label_6.setText(_translate("modelWIdget", "learning_rate(1e-3)："))
